# cocotb + Icarus para ov7670_sccb (maestro SCCB de config de la OV7670)
#   correr:  make -f Makefile.sccb
SIM ?= icarus
TOPLEVEL_LANG ?= verilog
PWD = $(shell pwd)
VERILOG_SOURCES += $(PWD)/../../cores/camera/ov7670_sccb.v
TOPLEVEL = ov7670_sccb
MODULE   = test_sccb
COMPILE_ARGS += -g2012
include $(shell cocotb-config --makefiles)/Makefile.sim
