# cocotb + Icarus para hysteresis_frame_bram_sync (lectura sincrona -> BRAM)
#   correr:  make -f Makefile.hystsync
SIM ?= icarus
TOPLEVEL_LANG ?= verilog
PWD = $(shell pwd)
VERILOG_SOURCES += $(PWD)/../hysteresis_frame_bram_sync.sv
TOPLEVEL = hysteresis_frame_bram_sync
MODULE   = test_hyst_ram
COMPILE_ARGS += -g2012
include $(shell cocotb-config --makefiles)/Makefile.sim
