SIM ?= icarus
TOPLEVEL_LANG ?= verilog
PWD = $(shell pwd)
VERILOG_SOURCES += $(PWD)/../tb_dma_top.sv $(PWD)/../filter_dma.sv $(PWD)/../dpram.sv \
  $(PWD)/../sobel_compass_control.sv $(PWD)/../sobel_compass_core.sv \
  $(PWD)/../canny_control.sv $(PWD)/../canny_full_core.sv
TOPLEVEL = tb_dma_top
MODULE   = test_dma
COMPILE_ARGS += -g2012
include $(shell cocotb-config --makefiles)/Makefile.sim
