SIM ?= icarus
TOPLEVEL_LANG ?= verilog
PWD = $(shell pwd)
VERILOG_SOURCES += $(PWD)/../soc_dma_top.sv $(PWD)/../bus_arbiter.sv $(PWD)/../filter_dma_bus.sv \
  $(PWD)/../spram.sv $(PWD)/../sobel_compass_control.sv $(PWD)/../sobel_compass_core.sv \
  $(PWD)/../canny_control.sv $(PWD)/../canny_full_core.sv
TOPLEVEL = soc_dma_top
MODULE   = test_soc_dma
COMPILE_ARGS += -g2012
include $(shell cocotb-config --makefiles)/Makefile.sim
