# cocotb + Icarus para hysteresis_frame_bram (version BRAM, line buffers)
#   correr:  make -f Makefile.hystbram
SIM ?= icarus
TOPLEVEL_LANG ?= verilog
PWD = $(shell pwd)
VERILOG_SOURCES += $(PWD)/../hysteresis_frame_bram.sv
TOPLEVEL = hysteresis_frame_bram
MODULE   = test_hyst_ram
COMPILE_ARGS += -g2012
include $(shell cocotb-config --makefiles)/Makefile.sim
