# cocotb + Icarus para nms_core
#   correr:  make -f Makefile.nms
SIM ?= icarus
TOPLEVEL_LANG ?= verilog
PWD = $(shell pwd)
VERILOG_SOURCES += $(PWD)/../nms_core.sv
TOPLEVEL = nms_core
MODULE   = test_nms
COMPILE_ARGS += -g2012
include $(shell cocotb-config --makefiles)/Makefile.sim
