# cocotb + Icarus para nms_control (streaming)
#   correr:  make -f Makefile.nms_ctrl
SIM ?= icarus
TOPLEVEL_LANG ?= verilog
PWD = $(shell pwd)
VERILOG_SOURCES += $(PWD)/../nms_control.sv
VERILOG_SOURCES += $(PWD)/../nms_core.sv
TOPLEVEL = nms_control
MODULE   = test_nms_control
COMPILE_ARGS += -g2012
include $(shell cocotb-config --makefiles)/Makefile.sim
