SIM ?= icarus
TOPLEVEL_LANG ?= verilog
PWD = $(shell pwd)
VERILOG_SOURCES += $(PWD)/../peripheral_sobel.v $(PWD)/../sobel_compass_control.sv \
  $(PWD)/../sobel_compass_core.sv $(PWD)/../canny_control.sv $(PWD)/../canny_full_core.sv
TOPLEVEL = peripheral_sobel
MODULE   = test_peripheral
COMPILE_ARGS += -g2012
include $(shell cocotb-config --makefiles)/Makefile.sim
