# cocotb + Icarus para hysteresis_frame_ram (histeresis transitiva sintetizable)
#   correr:  make -f Makefile.hystram
SIM ?= icarus
TOPLEVEL_LANG ?= verilog
PWD = $(shell pwd)
VERILOG_SOURCES += $(PWD)/../hysteresis_frame_ram.sv
TOPLEVEL = hysteresis_frame_ram
MODULE   = test_hyst_ram
COMPILE_ARGS += -g2012
include $(shell cocotb-config --makefiles)/Makefile.sim
