# cocotb + Icarus para canny_modular_full_bram (cadena + histeresis BRAM end-to-end)
#   correr:  make -f Makefile.modfullbram
SIM ?= icarus
TOPLEVEL_LANG ?= verilog
PWD = $(shell pwd)
VERILOG_SOURCES += $(PWD)/../canny_modular_full_bram.sv
VERILOG_SOURCES += $(PWD)/../canny_modular_top.sv
VERILOG_SOURCES += $(PWD)/../sobel_compass_control.sv
VERILOG_SOURCES += $(PWD)/../sobel_compass_core.sv
VERILOG_SOURCES += $(PWD)/../nms_control.sv
VERILOG_SOURCES += $(PWD)/../nms_core.sv
VERILOG_SOURCES += $(PWD)/../canny_grad_threshold_core.sv
VERILOG_SOURCES += $(PWD)/../isqrt.sv
VERILOG_SOURCES += $(PWD)/../hysteresis_frame_bram_sync.sv
TOPLEVEL = canny_modular_full_bram
MODULE   = test_modular_full_bram
COMPILE_ARGS += -g2012
include $(shell cocotb-config --makefiles)/Makefile.sim
