SIM ?= icarus
TOPLEVEL_LANG ?= verilog
PWD = $(shell pwd)
VERILOG_SOURCES += $(PWD)/../canny_hysteresis_frame.sv
TOPLEVEL = canny_hysteresis_frame
MODULE   = test_hysteresis
COMPILE_ARGS += -g2012
include $(shell cocotb-config --makefiles)/Makefile.sim
