// AUTO-GENERADO. Canny 5x5 combinacional: ventana (K+2)x(K+2)=7x7 ->
//   suaviza la vecindad 3x3 del centro con gaussian5x5 -> gradiente -> doble umbral.
//   pixel (r,c) en win_i[PIX*(r*7+c) +: PIX].  NMS+histeresis = futuro (no por-pixel).
`default_nettype none
module canny_top_5x5 #(parameter integer PIX=8, parameter integer USE_SQRT=0)(
    input  wire [7*7*PIX-1:0] win_i,
    input  wire [PIX+3:0] low_i, high_i,
    output wire [PIX+3:0] g_low_o, g_high_o,
    output wire [1:0]     class_o,
    output wire [(PIX+4+1)/2:0] combo_o);
    wire [PIX-1:0] sm [0:8];   // 3x3 suavizado
    // posicion gradiente g=0  centro suavizado (2,2)
    wire [25*PIX-1:0] sub0;
    assign sub0[PIX*0 +: PIX] = win_i[PIX*0 +: PIX];
    assign sub0[PIX*1 +: PIX] = win_i[PIX*1 +: PIX];
    assign sub0[PIX*2 +: PIX] = win_i[PIX*2 +: PIX];
    assign sub0[PIX*3 +: PIX] = win_i[PIX*3 +: PIX];
    assign sub0[PIX*4 +: PIX] = win_i[PIX*4 +: PIX];
    assign sub0[PIX*5 +: PIX] = win_i[PIX*7 +: PIX];
    assign sub0[PIX*6 +: PIX] = win_i[PIX*8 +: PIX];
    assign sub0[PIX*7 +: PIX] = win_i[PIX*9 +: PIX];
    assign sub0[PIX*8 +: PIX] = win_i[PIX*10 +: PIX];
    assign sub0[PIX*9 +: PIX] = win_i[PIX*11 +: PIX];
    assign sub0[PIX*10 +: PIX] = win_i[PIX*14 +: PIX];
    assign sub0[PIX*11 +: PIX] = win_i[PIX*15 +: PIX];
    assign sub0[PIX*12 +: PIX] = win_i[PIX*16 +: PIX];
    assign sub0[PIX*13 +: PIX] = win_i[PIX*17 +: PIX];
    assign sub0[PIX*14 +: PIX] = win_i[PIX*18 +: PIX];
    assign sub0[PIX*15 +: PIX] = win_i[PIX*21 +: PIX];
    assign sub0[PIX*16 +: PIX] = win_i[PIX*22 +: PIX];
    assign sub0[PIX*17 +: PIX] = win_i[PIX*23 +: PIX];
    assign sub0[PIX*18 +: PIX] = win_i[PIX*24 +: PIX];
    assign sub0[PIX*19 +: PIX] = win_i[PIX*25 +: PIX];
    assign sub0[PIX*20 +: PIX] = win_i[PIX*28 +: PIX];
    assign sub0[PIX*21 +: PIX] = win_i[PIX*29 +: PIX];
    assign sub0[PIX*22 +: PIX] = win_i[PIX*30 +: PIX];
    assign sub0[PIX*23 +: PIX] = win_i[PIX*31 +: PIX];
    assign sub0[PIX*24 +: PIX] = win_i[PIX*32 +: PIX];
    gaussian5x5 #(.PIX(PIX)) ug0 (.win_i(sub0), .gray_o(sm[0]));
    // posicion gradiente g=1  centro suavizado (2,3)
    wire [25*PIX-1:0] sub1;
    assign sub1[PIX*0 +: PIX] = win_i[PIX*1 +: PIX];
    assign sub1[PIX*1 +: PIX] = win_i[PIX*2 +: PIX];
    assign sub1[PIX*2 +: PIX] = win_i[PIX*3 +: PIX];
    assign sub1[PIX*3 +: PIX] = win_i[PIX*4 +: PIX];
    assign sub1[PIX*4 +: PIX] = win_i[PIX*5 +: PIX];
    assign sub1[PIX*5 +: PIX] = win_i[PIX*8 +: PIX];
    assign sub1[PIX*6 +: PIX] = win_i[PIX*9 +: PIX];
    assign sub1[PIX*7 +: PIX] = win_i[PIX*10 +: PIX];
    assign sub1[PIX*8 +: PIX] = win_i[PIX*11 +: PIX];
    assign sub1[PIX*9 +: PIX] = win_i[PIX*12 +: PIX];
    assign sub1[PIX*10 +: PIX] = win_i[PIX*15 +: PIX];
    assign sub1[PIX*11 +: PIX] = win_i[PIX*16 +: PIX];
    assign sub1[PIX*12 +: PIX] = win_i[PIX*17 +: PIX];
    assign sub1[PIX*13 +: PIX] = win_i[PIX*18 +: PIX];
    assign sub1[PIX*14 +: PIX] = win_i[PIX*19 +: PIX];
    assign sub1[PIX*15 +: PIX] = win_i[PIX*22 +: PIX];
    assign sub1[PIX*16 +: PIX] = win_i[PIX*23 +: PIX];
    assign sub1[PIX*17 +: PIX] = win_i[PIX*24 +: PIX];
    assign sub1[PIX*18 +: PIX] = win_i[PIX*25 +: PIX];
    assign sub1[PIX*19 +: PIX] = win_i[PIX*26 +: PIX];
    assign sub1[PIX*20 +: PIX] = win_i[PIX*29 +: PIX];
    assign sub1[PIX*21 +: PIX] = win_i[PIX*30 +: PIX];
    assign sub1[PIX*22 +: PIX] = win_i[PIX*31 +: PIX];
    assign sub1[PIX*23 +: PIX] = win_i[PIX*32 +: PIX];
    assign sub1[PIX*24 +: PIX] = win_i[PIX*33 +: PIX];
    gaussian5x5 #(.PIX(PIX)) ug1 (.win_i(sub1), .gray_o(sm[1]));
    // posicion gradiente g=2  centro suavizado (2,4)
    wire [25*PIX-1:0] sub2;
    assign sub2[PIX*0 +: PIX] = win_i[PIX*2 +: PIX];
    assign sub2[PIX*1 +: PIX] = win_i[PIX*3 +: PIX];
    assign sub2[PIX*2 +: PIX] = win_i[PIX*4 +: PIX];
    assign sub2[PIX*3 +: PIX] = win_i[PIX*5 +: PIX];
    assign sub2[PIX*4 +: PIX] = win_i[PIX*6 +: PIX];
    assign sub2[PIX*5 +: PIX] = win_i[PIX*9 +: PIX];
    assign sub2[PIX*6 +: PIX] = win_i[PIX*10 +: PIX];
    assign sub2[PIX*7 +: PIX] = win_i[PIX*11 +: PIX];
    assign sub2[PIX*8 +: PIX] = win_i[PIX*12 +: PIX];
    assign sub2[PIX*9 +: PIX] = win_i[PIX*13 +: PIX];
    assign sub2[PIX*10 +: PIX] = win_i[PIX*16 +: PIX];
    assign sub2[PIX*11 +: PIX] = win_i[PIX*17 +: PIX];
    assign sub2[PIX*12 +: PIX] = win_i[PIX*18 +: PIX];
    assign sub2[PIX*13 +: PIX] = win_i[PIX*19 +: PIX];
    assign sub2[PIX*14 +: PIX] = win_i[PIX*20 +: PIX];
    assign sub2[PIX*15 +: PIX] = win_i[PIX*23 +: PIX];
    assign sub2[PIX*16 +: PIX] = win_i[PIX*24 +: PIX];
    assign sub2[PIX*17 +: PIX] = win_i[PIX*25 +: PIX];
    assign sub2[PIX*18 +: PIX] = win_i[PIX*26 +: PIX];
    assign sub2[PIX*19 +: PIX] = win_i[PIX*27 +: PIX];
    assign sub2[PIX*20 +: PIX] = win_i[PIX*30 +: PIX];
    assign sub2[PIX*21 +: PIX] = win_i[PIX*31 +: PIX];
    assign sub2[PIX*22 +: PIX] = win_i[PIX*32 +: PIX];
    assign sub2[PIX*23 +: PIX] = win_i[PIX*33 +: PIX];
    assign sub2[PIX*24 +: PIX] = win_i[PIX*34 +: PIX];
    gaussian5x5 #(.PIX(PIX)) ug2 (.win_i(sub2), .gray_o(sm[2]));
    // posicion gradiente g=3  centro suavizado (3,2)
    wire [25*PIX-1:0] sub3;
    assign sub3[PIX*0 +: PIX] = win_i[PIX*7 +: PIX];
    assign sub3[PIX*1 +: PIX] = win_i[PIX*8 +: PIX];
    assign sub3[PIX*2 +: PIX] = win_i[PIX*9 +: PIX];
    assign sub3[PIX*3 +: PIX] = win_i[PIX*10 +: PIX];
    assign sub3[PIX*4 +: PIX] = win_i[PIX*11 +: PIX];
    assign sub3[PIX*5 +: PIX] = win_i[PIX*14 +: PIX];
    assign sub3[PIX*6 +: PIX] = win_i[PIX*15 +: PIX];
    assign sub3[PIX*7 +: PIX] = win_i[PIX*16 +: PIX];
    assign sub3[PIX*8 +: PIX] = win_i[PIX*17 +: PIX];
    assign sub3[PIX*9 +: PIX] = win_i[PIX*18 +: PIX];
    assign sub3[PIX*10 +: PIX] = win_i[PIX*21 +: PIX];
    assign sub3[PIX*11 +: PIX] = win_i[PIX*22 +: PIX];
    assign sub3[PIX*12 +: PIX] = win_i[PIX*23 +: PIX];
    assign sub3[PIX*13 +: PIX] = win_i[PIX*24 +: PIX];
    assign sub3[PIX*14 +: PIX] = win_i[PIX*25 +: PIX];
    assign sub3[PIX*15 +: PIX] = win_i[PIX*28 +: PIX];
    assign sub3[PIX*16 +: PIX] = win_i[PIX*29 +: PIX];
    assign sub3[PIX*17 +: PIX] = win_i[PIX*30 +: PIX];
    assign sub3[PIX*18 +: PIX] = win_i[PIX*31 +: PIX];
    assign sub3[PIX*19 +: PIX] = win_i[PIX*32 +: PIX];
    assign sub3[PIX*20 +: PIX] = win_i[PIX*35 +: PIX];
    assign sub3[PIX*21 +: PIX] = win_i[PIX*36 +: PIX];
    assign sub3[PIX*22 +: PIX] = win_i[PIX*37 +: PIX];
    assign sub3[PIX*23 +: PIX] = win_i[PIX*38 +: PIX];
    assign sub3[PIX*24 +: PIX] = win_i[PIX*39 +: PIX];
    gaussian5x5 #(.PIX(PIX)) ug3 (.win_i(sub3), .gray_o(sm[3]));
    // posicion gradiente g=4  centro suavizado (3,3)
    wire [25*PIX-1:0] sub4;
    assign sub4[PIX*0 +: PIX] = win_i[PIX*8 +: PIX];
    assign sub4[PIX*1 +: PIX] = win_i[PIX*9 +: PIX];
    assign sub4[PIX*2 +: PIX] = win_i[PIX*10 +: PIX];
    assign sub4[PIX*3 +: PIX] = win_i[PIX*11 +: PIX];
    assign sub4[PIX*4 +: PIX] = win_i[PIX*12 +: PIX];
    assign sub4[PIX*5 +: PIX] = win_i[PIX*15 +: PIX];
    assign sub4[PIX*6 +: PIX] = win_i[PIX*16 +: PIX];
    assign sub4[PIX*7 +: PIX] = win_i[PIX*17 +: PIX];
    assign sub4[PIX*8 +: PIX] = win_i[PIX*18 +: PIX];
    assign sub4[PIX*9 +: PIX] = win_i[PIX*19 +: PIX];
    assign sub4[PIX*10 +: PIX] = win_i[PIX*22 +: PIX];
    assign sub4[PIX*11 +: PIX] = win_i[PIX*23 +: PIX];
    assign sub4[PIX*12 +: PIX] = win_i[PIX*24 +: PIX];
    assign sub4[PIX*13 +: PIX] = win_i[PIX*25 +: PIX];
    assign sub4[PIX*14 +: PIX] = win_i[PIX*26 +: PIX];
    assign sub4[PIX*15 +: PIX] = win_i[PIX*29 +: PIX];
    assign sub4[PIX*16 +: PIX] = win_i[PIX*30 +: PIX];
    assign sub4[PIX*17 +: PIX] = win_i[PIX*31 +: PIX];
    assign sub4[PIX*18 +: PIX] = win_i[PIX*32 +: PIX];
    assign sub4[PIX*19 +: PIX] = win_i[PIX*33 +: PIX];
    assign sub4[PIX*20 +: PIX] = win_i[PIX*36 +: PIX];
    assign sub4[PIX*21 +: PIX] = win_i[PIX*37 +: PIX];
    assign sub4[PIX*22 +: PIX] = win_i[PIX*38 +: PIX];
    assign sub4[PIX*23 +: PIX] = win_i[PIX*39 +: PIX];
    assign sub4[PIX*24 +: PIX] = win_i[PIX*40 +: PIX];
    gaussian5x5 #(.PIX(PIX)) ug4 (.win_i(sub4), .gray_o(sm[4]));
    // posicion gradiente g=5  centro suavizado (3,4)
    wire [25*PIX-1:0] sub5;
    assign sub5[PIX*0 +: PIX] = win_i[PIX*9 +: PIX];
    assign sub5[PIX*1 +: PIX] = win_i[PIX*10 +: PIX];
    assign sub5[PIX*2 +: PIX] = win_i[PIX*11 +: PIX];
    assign sub5[PIX*3 +: PIX] = win_i[PIX*12 +: PIX];
    assign sub5[PIX*4 +: PIX] = win_i[PIX*13 +: PIX];
    assign sub5[PIX*5 +: PIX] = win_i[PIX*16 +: PIX];
    assign sub5[PIX*6 +: PIX] = win_i[PIX*17 +: PIX];
    assign sub5[PIX*7 +: PIX] = win_i[PIX*18 +: PIX];
    assign sub5[PIX*8 +: PIX] = win_i[PIX*19 +: PIX];
    assign sub5[PIX*9 +: PIX] = win_i[PIX*20 +: PIX];
    assign sub5[PIX*10 +: PIX] = win_i[PIX*23 +: PIX];
    assign sub5[PIX*11 +: PIX] = win_i[PIX*24 +: PIX];
    assign sub5[PIX*12 +: PIX] = win_i[PIX*25 +: PIX];
    assign sub5[PIX*13 +: PIX] = win_i[PIX*26 +: PIX];
    assign sub5[PIX*14 +: PIX] = win_i[PIX*27 +: PIX];
    assign sub5[PIX*15 +: PIX] = win_i[PIX*30 +: PIX];
    assign sub5[PIX*16 +: PIX] = win_i[PIX*31 +: PIX];
    assign sub5[PIX*17 +: PIX] = win_i[PIX*32 +: PIX];
    assign sub5[PIX*18 +: PIX] = win_i[PIX*33 +: PIX];
    assign sub5[PIX*19 +: PIX] = win_i[PIX*34 +: PIX];
    assign sub5[PIX*20 +: PIX] = win_i[PIX*37 +: PIX];
    assign sub5[PIX*21 +: PIX] = win_i[PIX*38 +: PIX];
    assign sub5[PIX*22 +: PIX] = win_i[PIX*39 +: PIX];
    assign sub5[PIX*23 +: PIX] = win_i[PIX*40 +: PIX];
    assign sub5[PIX*24 +: PIX] = win_i[PIX*41 +: PIX];
    gaussian5x5 #(.PIX(PIX)) ug5 (.win_i(sub5), .gray_o(sm[5]));
    // posicion gradiente g=6  centro suavizado (4,2)
    wire [25*PIX-1:0] sub6;
    assign sub6[PIX*0 +: PIX] = win_i[PIX*14 +: PIX];
    assign sub6[PIX*1 +: PIX] = win_i[PIX*15 +: PIX];
    assign sub6[PIX*2 +: PIX] = win_i[PIX*16 +: PIX];
    assign sub6[PIX*3 +: PIX] = win_i[PIX*17 +: PIX];
    assign sub6[PIX*4 +: PIX] = win_i[PIX*18 +: PIX];
    assign sub6[PIX*5 +: PIX] = win_i[PIX*21 +: PIX];
    assign sub6[PIX*6 +: PIX] = win_i[PIX*22 +: PIX];
    assign sub6[PIX*7 +: PIX] = win_i[PIX*23 +: PIX];
    assign sub6[PIX*8 +: PIX] = win_i[PIX*24 +: PIX];
    assign sub6[PIX*9 +: PIX] = win_i[PIX*25 +: PIX];
    assign sub6[PIX*10 +: PIX] = win_i[PIX*28 +: PIX];
    assign sub6[PIX*11 +: PIX] = win_i[PIX*29 +: PIX];
    assign sub6[PIX*12 +: PIX] = win_i[PIX*30 +: PIX];
    assign sub6[PIX*13 +: PIX] = win_i[PIX*31 +: PIX];
    assign sub6[PIX*14 +: PIX] = win_i[PIX*32 +: PIX];
    assign sub6[PIX*15 +: PIX] = win_i[PIX*35 +: PIX];
    assign sub6[PIX*16 +: PIX] = win_i[PIX*36 +: PIX];
    assign sub6[PIX*17 +: PIX] = win_i[PIX*37 +: PIX];
    assign sub6[PIX*18 +: PIX] = win_i[PIX*38 +: PIX];
    assign sub6[PIX*19 +: PIX] = win_i[PIX*39 +: PIX];
    assign sub6[PIX*20 +: PIX] = win_i[PIX*42 +: PIX];
    assign sub6[PIX*21 +: PIX] = win_i[PIX*43 +: PIX];
    assign sub6[PIX*22 +: PIX] = win_i[PIX*44 +: PIX];
    assign sub6[PIX*23 +: PIX] = win_i[PIX*45 +: PIX];
    assign sub6[PIX*24 +: PIX] = win_i[PIX*46 +: PIX];
    gaussian5x5 #(.PIX(PIX)) ug6 (.win_i(sub6), .gray_o(sm[6]));
    // posicion gradiente g=7  centro suavizado (4,3)
    wire [25*PIX-1:0] sub7;
    assign sub7[PIX*0 +: PIX] = win_i[PIX*15 +: PIX];
    assign sub7[PIX*1 +: PIX] = win_i[PIX*16 +: PIX];
    assign sub7[PIX*2 +: PIX] = win_i[PIX*17 +: PIX];
    assign sub7[PIX*3 +: PIX] = win_i[PIX*18 +: PIX];
    assign sub7[PIX*4 +: PIX] = win_i[PIX*19 +: PIX];
    assign sub7[PIX*5 +: PIX] = win_i[PIX*22 +: PIX];
    assign sub7[PIX*6 +: PIX] = win_i[PIX*23 +: PIX];
    assign sub7[PIX*7 +: PIX] = win_i[PIX*24 +: PIX];
    assign sub7[PIX*8 +: PIX] = win_i[PIX*25 +: PIX];
    assign sub7[PIX*9 +: PIX] = win_i[PIX*26 +: PIX];
    assign sub7[PIX*10 +: PIX] = win_i[PIX*29 +: PIX];
    assign sub7[PIX*11 +: PIX] = win_i[PIX*30 +: PIX];
    assign sub7[PIX*12 +: PIX] = win_i[PIX*31 +: PIX];
    assign sub7[PIX*13 +: PIX] = win_i[PIX*32 +: PIX];
    assign sub7[PIX*14 +: PIX] = win_i[PIX*33 +: PIX];
    assign sub7[PIX*15 +: PIX] = win_i[PIX*36 +: PIX];
    assign sub7[PIX*16 +: PIX] = win_i[PIX*37 +: PIX];
    assign sub7[PIX*17 +: PIX] = win_i[PIX*38 +: PIX];
    assign sub7[PIX*18 +: PIX] = win_i[PIX*39 +: PIX];
    assign sub7[PIX*19 +: PIX] = win_i[PIX*40 +: PIX];
    assign sub7[PIX*20 +: PIX] = win_i[PIX*43 +: PIX];
    assign sub7[PIX*21 +: PIX] = win_i[PIX*44 +: PIX];
    assign sub7[PIX*22 +: PIX] = win_i[PIX*45 +: PIX];
    assign sub7[PIX*23 +: PIX] = win_i[PIX*46 +: PIX];
    assign sub7[PIX*24 +: PIX] = win_i[PIX*47 +: PIX];
    gaussian5x5 #(.PIX(PIX)) ug7 (.win_i(sub7), .gray_o(sm[7]));
    // posicion gradiente g=8  centro suavizado (4,4)
    wire [25*PIX-1:0] sub8;
    assign sub8[PIX*0 +: PIX] = win_i[PIX*16 +: PIX];
    assign sub8[PIX*1 +: PIX] = win_i[PIX*17 +: PIX];
    assign sub8[PIX*2 +: PIX] = win_i[PIX*18 +: PIX];
    assign sub8[PIX*3 +: PIX] = win_i[PIX*19 +: PIX];
    assign sub8[PIX*4 +: PIX] = win_i[PIX*20 +: PIX];
    assign sub8[PIX*5 +: PIX] = win_i[PIX*23 +: PIX];
    assign sub8[PIX*6 +: PIX] = win_i[PIX*24 +: PIX];
    assign sub8[PIX*7 +: PIX] = win_i[PIX*25 +: PIX];
    assign sub8[PIX*8 +: PIX] = win_i[PIX*26 +: PIX];
    assign sub8[PIX*9 +: PIX] = win_i[PIX*27 +: PIX];
    assign sub8[PIX*10 +: PIX] = win_i[PIX*30 +: PIX];
    assign sub8[PIX*11 +: PIX] = win_i[PIX*31 +: PIX];
    assign sub8[PIX*12 +: PIX] = win_i[PIX*32 +: PIX];
    assign sub8[PIX*13 +: PIX] = win_i[PIX*33 +: PIX];
    assign sub8[PIX*14 +: PIX] = win_i[PIX*34 +: PIX];
    assign sub8[PIX*15 +: PIX] = win_i[PIX*37 +: PIX];
    assign sub8[PIX*16 +: PIX] = win_i[PIX*38 +: PIX];
    assign sub8[PIX*17 +: PIX] = win_i[PIX*39 +: PIX];
    assign sub8[PIX*18 +: PIX] = win_i[PIX*40 +: PIX];
    assign sub8[PIX*19 +: PIX] = win_i[PIX*41 +: PIX];
    assign sub8[PIX*20 +: PIX] = win_i[PIX*44 +: PIX];
    assign sub8[PIX*21 +: PIX] = win_i[PIX*45 +: PIX];
    assign sub8[PIX*22 +: PIX] = win_i[PIX*46 +: PIX];
    assign sub8[PIX*23 +: PIX] = win_i[PIX*47 +: PIX];
    assign sub8[PIX*24 +: PIX] = win_i[PIX*48 +: PIX];
    gaussian5x5 #(.PIX(PIX)) ug8 (.win_i(sub8), .gray_o(sm[8]));
    wire [9*PIX-1:0] smwin = {sm[8],sm[7],sm[6],sm[5],sm[4],sm[3],sm[2],sm[1],sm[0]};
    canny_datapath #(.PIX(PIX), .USE_SQRT(USE_SQRT)) u_dp (
        .sm_window_i(smwin), .low_i(low_i), .high_i(high_i),
        .g_low_o(g_low_o), .g_high_o(g_high_o), .class_o(class_o), .combo_o(combo_o));
endmodule
`default_nettype wire
